const qData = [
    {quizType:'html',question:'Which is the correct HTML element for the smallest heading?',answer1:'<h6>',answer2:'<h1>', correctAnswer:'h6'},
    {quizType:'html',question:'Which element means a line break?',answer1:'<br>',answer2:'<break>', correctAnswer:'<br>'},
    {quizType:'html',question:'How do you insert a hyperlink?',answer1:'<a url="www.link.com">Linked Text</a>',answer2:'<a href="www.link.com">Linked Text</a>', correctAnswer:'<a href="www.link.com">Linked Text</a>'},
    {quizType:'html',question:'Which attribute allows you to open a link in a new tab?',answer1:'target="newTab"',answer2:'target="_blank"', correctAnswer:'target="_blank"'},
    {quizType:'html',question:'Which HTML element creates a numbered list?',answer1:'<ol>',answer2:'<nl>', correctAnswer:'<ol>'},
    {quizType:'html',question:'Which HTML element creates a bulleted list?',answer1:'<bl>',answer2:'<ul>', correctAnswer:'<ul>'},
    {quizType:'html',question:'How do you create checkbox?',answer1:'<input type="checkbox">',answer2:'<input type="check">', correctAnswer:'<input type="checkbox">'},
    {quizType:'html',question:'How do you create a textbox?',answer1:'<input type="textbox">',answer2:'<input type="text">', correctAnswer:'<input type="text">'},
    {quizType:'html',question:'Which element creates a dropdown list?',answer1:'<dropdown>',answer2:'<select>', correctAnswer:'<select>'},
    {quizType:'html',question:'How do you add an image?',answer1:'<image src="image.jpeg>',answer2:'<img src="image.jpeg>', correctAnswer:'<img src="image.jpeg>'},
    {quizType:'js',question:'Inside which HTML element do we put the Javascript?',answer1:'<javascript>',answer2:'<script>', correctAnswer:'<script>'},
    {quizType:'js',question:'How do you write HELLO WORLD in an alert box?',answer1:'alert("Hello World")',answer2:'msg("Hello World")', correctAnswer:'alert("Hello World")'},
    {quizType:'js',question:'How do you create a function?',answer1:'function:myFunction()',answer2:'function = myFunction();', correctAnswer:'function = myFunction();'},
    {quizType:'js',question:'Whats the correct way to write an if statement?',answer1:'if (i == 5)',answer2:'if i = 5 then', correctAnswer:'if (i == 5)'},
    {quizType:'js',question:'How does a for loop start?',answer1:'for (i <= 5; i++)',answer2:'for (i = 0; i <= 5; i++)', correctAnswer:'for (i = 0; i <= 5; i++)'},
    {quizType:'js',question:'How do you round 7.25 to the nearest integer?',answer1:'Math.round(7.25)',answer2:'Math.int(7.25)', correctAnswer:'Math.round(7.25)'},
    {quizType:'js',question:'What event occurs when the user clicks an HTML element?',answer1:'onClick',answer2:'onChange', correctAnswer:'onClick'},
    {quizType:'js',question:'How do you declare a Javascript variable?',answer1:'var carName',answer2:'variable carName', correctAnswer:'var carName'},
    {quizType:'js',question:'Which operator is used to assign a value to a variable?',answer1:'var carName = Lincoln',answer2:'variable carName - Lincoln', correctAnswer:'var carName = Lincoln'},
    {quizType:'js',question:'Whats the correct JavaScript syntax to change the content of an HTML element?  <p id="demo">This is a demonstration.</p>',answer1:'document.getElementByName(“p”).innerHTML = “Hello World!”',answer2:'document.getElementById(“demo”).innerHTML = “Hello World!”', correctAnswer:'document.getElementById(“demo”).innerHTML = “Hello World!”'},
    {quizType:'css',question:' What is the correct way to externally link a CSS stylesheet in the HTML file?',answer1:'<style> href="style.css" <style>',answer2:'<link rel="stylesheet" type="text/css" href="style.css">', correctAnswer:'<link rel="stylesheet" type="text/css" href="style.css">'},
    {quizType:'css',question:'How would you set the background of your webpage to blue?',answer1:'body {background-color: blue;}',answer1:'', correctAnswer:'body background {blue;}'},
    {quizType:'css',question:'What does CSS stand for?',answer1:'Cascading Style Sheet',answer2:'Custom Style Sheet', correctAnswer:'Cascading Style Sheet'},
    {quizType:'css',question:'What property do you use to create rounded borders on a div?',answer1:'border-radius',answer2:'border-edge', correctAnswer:'border-radius'},
    {quizType:'css',question:'What would be the correct way to call this id for styling: "id=box" ',answer1:'box {}',answer2:' #box {}', correctAnswer:'#box {}'},
    {quizType:'css',question:'What property is used to create space around content inside an element with defined borders?',answer1:'Padding',answer2:'Margin', correctAnswer:'Padding'},
    {quizType:'css',question:'How do you change the font name?',answer1:'font-family',answer2:'font-type', correctAnswer:'font-family'},
    {quizType:'css',question:'What will the following command do: "text-transform: uppercase"',answer1:'Capitalize the first letter of each word in the assigned text',answer2:'Make all letters in the assigned text uppercase', correctAnswer:'Make all letters in the assigned text uppercase'},
    {quizType:'css',question:'What tag is used to add CSS inline in your HTML file?',answer1:'<css>',answer2:'<style>', correctAnswer:'<style>'},
    {quizType:'css',question:'Which one would create a bulleted list?',answer1:'<ul></ul>',answer2:'<li></li>', correctAnswer:'<ul></ul>'},
    {quizType:'git',question:'What command is used to upload changes to your repository that were made locally?',answer1:'git push',answer2:'git add', correctAnswer:'git push'},
    {quizType:'git',question:'"git add" does which of the following?',answer1:'Stages changes made to a file',answer2:'Adds a branch to your repository ', correctAnswer:'Stages changes made to a file'},
    {quizType:'git',question:'This file type is used to ensure certain file types are not added to your local Git repository:',answer1:'git.ignore',answer2:'.gitignore', correctAnswer:'.gitignore'},
    {quizType:'git',question:'What is the purpose of the command "git diff"?',answer1:'To display changes that were made but not yet staged',answer2:'To display changes that have been staged but not yet committed', correctAnswer:'To display changes that were made but not yet staged'},
    {quizType:'git',question:'What command shows the commit history for the current active branch?',answer1:'git status',answer2:'git log', correctAnswer:'git log'},
    {quizType:'git',question:'What command is used to locally download a remote repository?',answer1:'git clone',answer2:'git fetch', correctAnswer:'git clone'},
    {quizType:'git',question:'What is the correct order when uploading changes to your Git repository?',answer1:'git add / git commit / git push',answer2:'git commit / git add / git push', correctAnswer:'git add / git commit / git push'},
    {quizType:'git',question:'"git init" is used to do what?',answer1:'Set up a new Git repository',answer2:'Prepare changes made to current active ', correctAnswer:'Set up a new Git repository'},
    {quizType:'git',question:'How do you create and immediately switch to a new branch locally?',answer1:'git pull',answer2:'git checkout', correctAnswer:'git checkout'},
    {quizType:'git',question:'What is the opposite of "git clone"?',answer1:'git push',answer2:'git pull', correctAnswer:'git push'},
    {quizType:'cli',question:'What is the command to move from one directory to another?',answer1:'md',answer2:'cd', correctAnswer:'cd'},
    {quizType:'cli',question:'What is the command to see all files in a directory?',answer1:'ls',answer2:'gf', correctAnswer:'ls'},
    {quizType:'cli',question:'What is the command to create a file?',answer1:'create',answer2:'touch', correctAnswer:'touch'},
    {quizType:'cli',question:'What is the command to create a directory',answer1:'mkdir',answer2:'dircreate', correctAnswer:'mkdir'},
    {quizType:'cli',question:'When changeing directories, what should you use to go back to the parent directory?',answer1:'../',answer2:'.//', correctAnswer:'../'},
    {quizType:'cli',question:'Which command can be used to see all files in a directory (including hidden files)?',answer1:'ls -a',answer2:'sa -h', correctAnswer:'ls -a'},
    {quizType:'cli',question:'Which command can be used to show the content of a file on the command line?',answer1:'cont',answer2:'cat', correctAnswer:'cat'},
    {quizType:'cli',question:'How do you remove a file on the command line?',answer1:'rm "file name"',answer2:'rem - "file name"', correctAnswer:''},
    {quizType:'cli',question:'What command moves a file to another folder?',answer1:'rl',answer2:'mv', correctAnswer:'mv'},
    {quizType:'cli',question:'What does the "clear" command do?',answer1:'clears all of the files from a repository',answer2:'clears the command line of previous activity log', correctAnswer:'clears the command line of previous activity log'}
];

module.exports = {qData};